### ISSUE TITLE
Lua 5.4 compatibility

### ISSUE THREAD

**Issue by mna** [daurnimator/cqueues-pgsql#6]
Hello,

Is there anything blocking this module from working on Lua 5.4? It can't be installed at the moment as it depends on luapgsql which has the constraint `lua >= 5.1, < 5.4` on luarocks.

Thanks,
Martin

**Comment by daurnimator** [comment]
> Is there anything blocking this module from working on Lua 5.4? It can't be installed at the moment as it depends on luapgsql which has the constraint `lua >= 5.1, < 5.4` on luarocks.

I don't think so.

But you'll have to take that up with luapgsql.
